Fix error handling bug in tests
When the server does not boot instead of hitting line.nil? there was:

undefined method `include?' for nil:NilClass (NoMethodError)

This is easily fixed with the safe navigation operator.